### ISSUE TITLE
RemoteDisconnected('Remote end closed connection without response',)

### ISSUE THREAD

**Issue by faustinaSelvadeepa** [philipperemy/Stanford-OpenIE-Python#17] opened 2020-03-25 13:54 UTC
I am testing openie for various sample texts. Sometimes I get the results and sometimes it throws "connection aborted, Remotedisconnected ('Remote end closed connection without response',)" error.
I am using Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-1063-aws x86_64)
![Error](https://user-images.githubusercontent.com/36688776/77543764-23227300-6ece-11ea-9361-a0446e2149f5.PNG)

**Comment by philipperemy** [comment] 2020-03-26 13:58
@faustinaSelvadeepa sometimes means a lot or it happened once? It is maybe possible that the server is already started when this command is run.

**Comment by faustinaSelvadeepa** [comment] 2020-03-26 17:22
@philipperemy Thank you so much for responding back. It happened several times in a day. Should I close the server after every use? If so what is the right way to stop the server? else Is there a way to access the server multiple times?

**Comment by philipperemy** [comment] 2020-03-27 09:40
I checked a bit and could not reproduce the issue. Do you have an example that shows how you use it? @faustinaSelvadeepa

**Comment by faustinaSelvadeepa** [comment] 2020-03-28 06:22
Here is how i am using it, I have put everything in a function. When I make a call to this function multiple times I get "connection aborted" error at several tries. I am not sure what mistake i have made..could you please help me?
def get_triplets(text):
    pos_words = POS_words(text)
    processed_text = get_coref_text(text)
    with StanfordOpenIE() as client:
            triple_list = []
            for triple in client.annotate(processed_text):
                triple_list.append(triple)
    return triple_list

**Comment by philipperemy** [comment] 2020-03-28 06:37
Ah that's why then. StanfordOpenIE() should be instantiated only one. So either pass this object to the function, wrap this in an object or use `with StanfordOpenIE() as client:` at the beginning of your code.

**Comment by philipperemy** [comment] 2020-03-28 06:52
(I'll close this issue now. Feel free to re-open it if you have more questions)

**Closed by philipperemy** 2020-03-28 06:52 UTC
